apiVersion: v1
kind: Service
metadata:
  labels:
    app: webgoat
  name: webgoat
  namespace: webgoat
spec:
  ports:
  - name: webgoat
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: webgoat
  type: NodePort
status:
  loadBalancer: {}
