apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webgoat
  name: webgoat
  namespace: webgoat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webgoat
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webgoat
    spec:
      containers:
      - image: age68573/webgoat:1
        name: webgoat
        ports:
        - containerPort: 8080
        resources: {}
status: {}
